# Generated by Django 2.1.7 on 2019-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
